name: ClearLag
main: TStark\ClearLag\Main
version: 1.0.0
api: 5.0.0
author: TStark
website: https://mcpetools.surge.sh
description: A plugin to clean items dumped on the server.
icon: icon.png
