clear-interval: 120
clear-message: "§aGarbage collected successfully."
warning-message: "§cCollecting garbage in {time}..."
broadcast-interval: 10
broadcast-message: "§bThe items will be deleted in {time} seconds."
