clear-interval: 120
clear-message: "§aBasura recogida correctamente."
warning-message: "§cRecogiendo basura en {time}..."
broadcast-interval: 15
broadcast-message: "§bLos ítems serán borrados en {time} segundos."